
# Name for this experiment - will be used to name the output files and directories
experiment_name: "small_mvt_2_debug"

# Path Settings (relative to project root)
project_path: "."
data_path: "data"

# Data directories (will be directories in data_path)
raw_dir: "01_raw"
preprocessed_dir: "02_preprocessed"
feature_dir: "03_features"
ot_dir: "04_ot"
results_dir: "05_results"

# Name of the raw image file to be processed - should be in data_path/raw_dir
raw_image: "matched_data.nd2"

# Setting for the preprocessing pipeline
defaults:
  - _self_
  - preprocess: 4_cuts_small
  - detect_droplets: ransac3
  - extract_visual_embeddings: cl_efficientnet
  - track: param_search
  - generate_results: scaled_entries

# Skip steps if they have already been completed
skip_preprocessing: true # less than a few minutes for 4k*4k
skip_droplet_detection: true # about 5 minutes for 4k*4k
skip_droplet_patch_extraction: true # not very long either
skip_visual_embedding_extraction: true # 2 minutes
skip_tracking: false # 40 minutes 4k*4k on my laptop (Mike, on CPU!)
skip_results_generation: false

# Detail level of the progress indications
verbose: true
tqdm_disable: false

# Device Settings
device: cpu





