# Setting for the preprocessing pipeline
defaults:
  - _self_
  - extract_visual_embeddings: droplets_all # Config for the visual embedding extraction
  - track: medium_20000_best                # Config for the tracking - sinkhorn parameters, etc.
  - generate_results: scaled_entries_eval
  - evaluate: unbalanced_v1

# Name for this experiment - will be used to name the output files and directories
experiment_name: "large_mvt_6000"
# experiment_name: "medium_mvt_20000_frames_2345"

# Name of the simulated image file to be processed - should be in data_path/simulated_dir
simulated_image: "large_mvt_6000_droplets.csv"

# Paths to paired_patches and their metadata files - should be in data_path/feature_dir
paired_patches: "paired_patches_9_frames_13584_droplets.npy"
paired_patches_metadata: "paired_patches_9_frames_13584_droplets_metadata.csv"

# Path Settings (relative to project root)
project_path: "."
data_path: "evaluation"
checkpoint_dir: "checkpoints"

# Evaluation directories (will be directories in data_path)
simulated_dir: "01_simulated"
preprocessed_dir: "02_preprocessed"
feature_dir: "03_features"
ot_dir: "04_ot"
results_dir: "05_results"

# GT specification for patches extraction
extract_patches: false # If this is false, paired_patches file name will be used instead of generating
gt_data_path: "/home/weronika/Documents/masters/sem3/data_science_lab/data"
gt_experiment_name: "small_mvt_3_smaller"
gt_feature_dir: "03_features"
gt_results_dir: "05_results"
gt_frames: 9
gt_max_distance: 5 # We only keep droplets that moved less than this distance
gt_margin: 20 # We only keep trajectories with droplets that are not next to the cut edge
gt_uncertainty_threshold: 0.95 # Only trajectories with greater mean uncertainty are kept

# Skip steps if they have already been completed
skip_preprocessing: true
skip_visual_embedding_extraction: false
skip_tracking: true
skip_results_generation: true
skip_trajectory_generation: true
skip_scoring: true
skip_calibration_plot: true

# Detail level of the progress indications
verbose: true
tqdm_disable: false

# Device Settings
device: cpu

# wandb
wandb: false

# sweep
sweep: false