# Description: Configuration file for the visualizer - see README.md for more details

# Name of the results file to visualize
results: "dropped_trajectories_y0_x0_basic.csv"
raw_image: "Small mvt 1.nd2"

# Name of the experiment to visualize
experiment_name: "small_mvt_3_full"

# Path Settings (relative to project root)
project_path: "."
data_path: "data"

# Data directories (relative to data_path)
raw_dir: "01_raw"
results_dir: "05_results"

# Frames range to consider
frame_range: [1,5] # [first_frame, last_frame] - If null, all frames are considered. 
