# Description: Configuration file for the visualizer - see README.md for more details

# Name of the results file to visualize
#results: "unfiltered_trajectories_y0_x0.csv"
results: "filtered_trajectories_y0_x0_basic.csv"
# results: "dropped_trajectories_y0_x0_basic.csv"

raw_image: "Small mvt 1.nd2"
#raw_image: "Small mvt 3.nd2"

# Name of the experiment to visualize
#experiment_name: "medium_mvt_6000"
experiment_name: "small_mvt_demo"
# experiment_name: "small_mvt_1_4cuts"
# experiment_name: "MedMov_LargeDrop_Barcoded"

evaluation_results: false # Whether we are plotting evaluation results or not

# Path Settings (relative to project root)
project_path: "."
data_path: "data"

# Data directories (relative to data_path)
raw_dir: "01_raw"
results_dir: "05_results"

# Frames range to consider
#frame_range: null
frame_range: [0,3] # [first_frame, last_frame] - If null, all frames are considered. 
